# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: 'build'
      - './dist/simple-userscript.exe -f example.js'

  build:
    cmds:
      - 'rm -rf dist'
      - 'mkdir dist'
      - 'CGO_ENABLED=0 go build -ldflags "-s -w " -trimpath -o dist .'